export const mockApiFirstLatter = () => Promise.resolve({
  json: () => Promise.resolve({
    meals: [
      {
        idMeal: '52768',
        strMeal: 'Apple Frangipan Tart',
        strDrinkAlternate: null,
        strCategory: 'Dessert',
        strArea: 'British',
        strInstructions: '',
        strMealThumb:
              'https://www.themealdb.com/images/media/meals/wxywrq1468235067.jpg',
        strTags: 'Tart,Baking,Fruity',
        strYoutube: 'https://www.youtube.com/watch?v=rp8Slv4INLk',
        strIngredient1: 'digestive biscuits',
        strIngredient2: 'butter',
        strIngredient3: 'Bramley apples',
        strIngredient4: 'butter, softened',
        strIngredient5: 'caster sugar',
        strIngredient6: 'free-range eggs, beaten',
        strIngredient7: 'ground almonds',
        strIngredient8: 'almond extract',
        strIngredient9: 'flaked almonds',
        strMeasure1: '175g/6oz',
        strMeasure2: '75g/3oz',
        strMeasure3: '200g/7oz',
        strMeasure4: '75g/3oz',
        strMeasure5: '75g/3oz',
        strMeasure6: '2',
        strMeasure7: '75g/3oz',
        strMeasure8: '1 tsp',
        strMeasure9: '50g/1\u00beoz',
        strMeasure10: '',
        strMeasure11: '',
        strMeasure12: '',
        strMeasure13: '',
        strMeasure14: '',
        strMeasure15: '',
        strMeasure16: null,
        strMeasure17: null,
        strMeasure18: null,
        strMeasure19: null,
        strMeasure20: null,
        strSource: null,
        strImageSource: null,
        strCreativeCommonsConfirmed: null,
        dateModified: null,
      },
    ],
  }),
});
