export const mockApiFirstLatter = {
  drinks: [
    {
      idDrink: '15328',
      strDrink: 'Zorro',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Coffee / Tea',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Coffee Mug',
      strInstructions: 'add all and pour black coffee and add whipped cream on top.',
      strInstructionsES: null,
      strInstructionsDE: '',
      strInstructionsFR: null,
      strInstructionsIT: '',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/kvvd4z1485621283.jpg',
      strIngredient1: 'Sambuca',
      strIngredient2: 'Baileys irish cream',
      strIngredient3: 'White Creme de Menthe',
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '2 cl ',
      strMeasure2: '2 cl ',
      strMeasure3: '2 cl ',
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-01-28 16:34:43',
    },
    {
      idDrink: '14888',
      strDrink: 'Zinger',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Soft Drink',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Highball glass',
      strInstructions: '',
      strInstructionsES: null,
      strInstructionsDE: '',
      strInstructionsFR: null,
      strInstructionsIT: 'Prendi un bicchierino e versa tre shot di grappa.',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/iixv4l1485620014.jpg',
      strIngredient1: 'Peachtree schnapps',
      strIngredient2: 'Surge',
      strIngredient3: null,
      strIngredient4: null,
      strIngredient5: null,
      strIngredient6: null,
      strIngredient7: null,
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '4 shots ',
      strMeasure2: '4 shots ',
      strMeasure3: null,
      strMeasure4: null,
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-01-28 16:13:34',
    },
    {
      idDrink: '15691',
      strDrink: 'Zoksel',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Soft Drink',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Beer pilsner',
      strInstructions: '',
      strInstructionsES: null,
      strInstructionsDE: '',
      strInstructionsFR: null,
      strInstructionsIT: '',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/ft8ed01485620930.jpg',
      strIngredient1: 'Beer',
      strIngredient2: 'Root beer',
      strIngredient3: 'Lemonade',
      strIngredient4: 'Coca-Cola',
      strIngredient5: '7-Up',
      strIngredient6: 'Creme de Cassis',
      strIngredient7: 'Lemon',
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: null,
      strMeasure2: null,
      strMeasure3: null,
      strMeasure4: ' slice\n',
      strMeasure5: null,
      strMeasure6: null,
      strMeasure7: null,
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-01-28 16:28:50',
    },
    {
      idDrink: '17241',
      strDrink: 'Zombie',
      strDrinkAlternate: null,
      strTags: null,
      strVideo: null,
      strCategory: 'Cocktail',
      strIBA: null,
      strAlcoholic: 'Alcoholic',
      strGlass: 'Hurricane glass',
      strInstructions: '',
      strInstructionsES: null,
      strInstructionsDE: '',
      strInstructionsFR: null,
      strInstructionsIT: '',
      'strInstructionsZH-HANS': null,
      'strInstructionsZH-HANT': null,
      strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/2en3jk1509557725.jpg',
      strIngredient1: 'Rum',
      strIngredient2: 'Gold rum',
      strIngredient3: '151 proof rum',
      strIngredient4: 'Pernod',
      strIngredient5: 'Grenadine',
      strIngredient6: 'Lime Juice',
      strIngredient7: 'Angostura Bitters',
      strIngredient8: null,
      strIngredient9: null,
      strIngredient10: null,
      strIngredient11: null,
      strIngredient12: null,
      strIngredient13: null,
      strIngredient14: null,
      strIngredient15: null,
      strMeasure1: '1 1/2 oz',
      strMeasure2: '1 1/2 oz',
      strMeasure3: '1 oz',
      strMeasure4: '1 tsp',
      strMeasure5: '1 tsp',
      strMeasure6: '1 tsp',
      strMeasure7: '1 drop',
      strMeasure8: null,
      strMeasure9: null,
      strMeasure10: null,
      strMeasure11: null,
      strMeasure12: null,
      strMeasure13: null,
      strMeasure14: null,
      strMeasure15: null,
      strImageSource: null,
      strImageAttribution: null,
      strCreativeCommonsConfirmed: 'No',
      dateModified: '2017-11-01 17:35:26',
    },
  ],
};
